# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  ruby: circleci/ruby@2.0.0
  browser-tools: circleci/browser-tools@1.4.1
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs

jobs:
  build:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/configuration-reference/#executor-job
    docker:
      - image: cimg/ruby:3.0.2-node
        environment:
          RAILS_ENV: test
          RACK_ENV: test
          DATABASE_URL: "postgres://user:@localhost:5432/phuketmanage_test"
          S3_BUCKET: 'test'
      - image: cimg/postgres:13.10
        environment:
          POSTGRES_USER: user
          POSTGRES_DB: db
      - image: cimg/node:15.0.1-browsers
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
      - checkout
      - ruby/install-deps
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run: |
          ruby --version
          node --version
          # java --version
          google-chrome --version
          sudo bundle install
          bundle exec rails db:create db:schema:load
          bundle exec rake
          bundle exec rspec
      - store_artifacts:
          path: test-results
          destination: test-results
