default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: sergey
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: phuketmanage_development

test:
  <<: *default
  database: phuketmanage_test

production:
  <<: *default
  database: phuketmanage_production
  username: phuketmanage
  password: <%= ENV["PHUKETMANAGE_DATABASE_PASSWORD"] %>
