S3_BUCKET: phuketmanage-development
AWS_ACCESS_KEY_ID: AKIASANYCWRAMOW5GHMY
AWS_SECRET_ACCESS_KEY: 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
TWILIO_ACCOUNT_SID: AC3cdb55fc7bffef152d2bcc06a98f5c49
TWILIO_AUTH_TOKEN: 9d342694d06edb329cb7db835a775b0c
TWILIO_PHONE_NUMBER: '+19089750732'
GOOGLE_TRANSLATE_API_KEY: AIzaSyDZps_zndKZ7PopkO46xAfJhuwFWCHbiz8
EXCHANGE_APP_ID: de3711d131664959a59875a310fa142d